### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by andreaslarssen** [gfreeau/GfreeauGetJWTBundle#1]
Hi.

First, I just want to say great project, just what I was looking for. 

I'm a Symfony noob, and been fiddling around with your bundle, trying to authenticate through an Angular frontend, and so far I've managed to get the token just fine. 

The problem starts when I'm trying to access other methods than the getToken one (I renamed it to authenticate). I'm getting a 401 status, and my symfony security log gives me this error: "A Token was not found in the SecurityContext".

I've Googled around, and see that this is an error not in direct relation to your lib. But I'm not sure if I've missed some basic Symfony setup, or if it's my integration of your lib that gives me the error. Or my implementation of the Userinterface for that matter. My setup did work with a basic form_login with a database, though. All I did after that is changing my firewall settings.

You wouldn't have any leads for me as for what could be wrong, or what I should check?

Here's my security.yml for reference:

``` yml
security:
    encoders:
        App\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database:
            entity: { class: AppUserBundle:User, property: email }

    firewalls:
        gettoken:
            pattern:  ^/v1/users/authenticate$
            provider: database
            stateless: true
            gfreeau_get_jwt:
                username_parameter: email
                password_parameter: password
                post_only: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt:
                authorization_header: 
                    enabled: true
                    prefix:  Bearer
                query_parameter:    
                    enabled: true
                    name:    bearer
                throw_exceptions: false     
                create_entry_point: true    
```
