### ISSUE TITLE
Symfony 2.8 upgrade breaks this bundle

### ISSUE THREAD

**Issue by guilhermeblanco** [gfreeau/GfreeauGetJWTBundle#12]
Error:

```bash
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider::__construct() must be an instance of Symfony\Component\Security\Core\User\UserCheckerInterface, string given, called in /run/shm/user/cache/dev/appDevDebugProjectContainer.php on line 10854 and defined
```

**Comment by hacfi** [comment]
@guilhermeblanco That’s odd. If you have a look at https://github.com/gfreeau/GfreeauGetJWTBundle/blob/master/DependencyInjection/Security/Factory/GetJWTFactory.php#L19-L23 and compare it to https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/HttpDigestFactory.php#L29-L33 it’s the same and should work!? Can you paste the generated container code (I think it’s the `getSecurity_Authentication_ManagerService` method)?

**Comment by guilhermeblanco** [comment]
```php
    protected function getSecurity_Authentication_ManagerService()
    {
        $a = $this->get('debug.event_dispatcher');
        $b = $this->get('doctrine');

        $c = new \Symfony\Bridge\Doctrine\Security\User\EntityUserProvider($b, 'MyLane\\DirectoryBundle\\Entity\\User', 'username', NULL);

        $d = new \MyLane\DirectoryBundle\Provider\JWTProvider($c, $this->get('lexik_jwt_authentication.jwt_manager'), $a);
        $d->setUserIdentityField('username');

        $this->services['security.authentication.manager'] = $instance = new \Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager(array(0 => new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider($c, '', 'login', $this->get('security.encoder_factory'), true), 1 => $d, 2 => new \Symfony\Component\Security\Core\Authentication\Provider\AnonymousAuthenticationProvider('565ce02b6e1638.52413211')), true);

        $instance->setEventDispatcher($a);

        return $instance;
    }
```

**Comment by guilhermeblanco** [comment]
My security.yml

```yaml
security:
    firewalls:
        login:
            pattern:   '^/users/login'
            stateless: true
            gfreeau_get_jwt:
                username_parameter:      'username'
                password_parameter:      'password'
                post_only:               true
                authentication_provider: 'security.authentication.provider.dao'
                success_handler:         'app.handler.authentication_success'
                failure_handler:         'app.handler.authentication_failure'
```
